package TasteProfile;


/**
* TasteProfile/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Wednesday, October 3, 2018 2:05:50 PM CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given song was played by all the users*/
  int getTimesPlayed (String song_id);

  /* Returns how many times a given song was played by a given user*/
  int getTimesPlayedByUser (String user_id, String song_id);

  /* Returns the three users with the most plays of specified song*/
  TasteProfile.TopThree getTopThreeUsersBySong (String song_id);

  //string getTopThreeUsersBySong(in string song_id);
  TasteProfile.UserProfile getUserProfile (String user_id);
} // interface ProfilerOperations
