package TasteProfile;


/**
* TasteProfile/SongDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Tuesday, October 2, 2018 12:57:26 PM CEST
*/


/*
valuetype UserCounter {
public string user_id;
public long songid_play_time;
};

valuetype TopThree {
public sequence<UserCounter> topThreeUsers;
};

valuetype SongProfile {
public long total_play_count;
public TopThree top_three_users;
};*/
public class SongDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new SongImpl ());
  }
}
