package TasteProfile;


/**
* TasteProfile/UserCounterDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Wednesday, October 3, 2018 2:05:50 PM CEST
*/

public class UserCounterDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new UserCounterImpl ());
  }
}
