package TasteProfile;


/**
* TasteProfile/UserProfileDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Tuesday, October 2, 2018 12:57:26 PM CEST
*/

public class UserProfileDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new UserProfileImpl ());
  }
}
